language: python
services:
  - docker
python:
  - "3.8"
install:
  - pip install nox
script:
  - nox -s flake8
  - nox -s tests_unit
  - docker-compose up -d
  - sleep 30
  - docker ps
  - docker-compose down